(* OCaml module generated by the BNF converter *)

type nat = Nat of string
and int = Int of string
and prog =
   Code of instr * instr list

and instr =
   IPUSH of cType * data
 | IADD

and data =
   DInt of int

and cType =
   CInt

