(* File generated by the BNF Converter (bnfc 2.9.3). *)

open Lexing

let parse (c : in_channel) : AbsMichelson.prog =
    ParMichelson.pProg LexMichelson.token (Lexing.from_channel c)
;;

let showTree (t : AbsMichelson.prog) : string =
    "[Abstract syntax]\n\n"^
    (fun x -> ShowMichelson.show (ShowMichelson.showProg x)) t^ "\n\n"^
    "[Linearized tree]\n\n"^
    PrintMichelson.printTree PrintMichelson.prtProg t^ "\n"
;;

let main () =
    let channel =
        if Array.length Sys.argv > 1 then open_in Sys.argv.(1)
        else stdin
    in
    try print_string (showTree (parse channel));
        flush stdout;
        exit 0
    with BNFC_Util.Parse_error (start_pos, end_pos) ->
        Printf.printf "Parse error at %d.%d-%d.%d\n"
            start_pos.pos_lnum (start_pos.pos_cnum - start_pos.pos_bol + 1)
            end_pos.pos_lnum (end_pos.pos_cnum - end_pos.pos_bol + 1);
        exit 1
;;

main ();;
