.PHONY: fmbc2021.zip

fmbc2021.zip:
	zip fmbc2021.zip \
	fmbc2021/oasics-logo-bw.pdf \
	fmbc2021/biblio.bib \
	fmbc2021/cc-by.pdf \
	fmbc2021/macros.tex \
	fmbc2021/oasics-v2021.cls \
	fmbc2021/orcid.pdf \
	fmbc2021/fmbc-main.pdf \
	fmbc2021/fmbc-main.tex

clean:
	rm fmbc2021.zip


