-- Haskell module generated by the BNF converter

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Michelson.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Michelson.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transInt :: Michelson.Abs.Int -> Result
transInt x = case x of
  Michelson.Abs.Int string -> failure x

transNat :: Michelson.Abs.Nat -> Result
transNat x = case x of
  Michelson.Abs.Nat string -> failure x

transStr :: Michelson.Abs.Str -> Result
transStr x = case x of
  Michelson.Abs.Str string -> failure x

transHex :: Michelson.Abs.Hex -> Result
transHex x = case x of
  Michelson.Abs.Hex string -> failure x

transProg :: Michelson.Abs.Prog -> Result
transProg x = case x of
  Michelson.Abs.Code instr instrs -> failure x

transPairSeq :: Michelson.Abs.PairSeq -> Result
transPairSeq x = case x of
  Michelson.Abs.DPairSeq1 data_1 data_2 -> failure x
  Michelson.Abs.DPairSeq2 data_ pairseq -> failure x

transMapSeq :: Michelson.Abs.MapSeq -> Result
transMapSeq x = case x of
  Michelson.Abs.DMapSeq1 data_1 data_2 -> failure x
  Michelson.Abs.DMapSeq2 data_1 data_2 mapseq -> failure x

transData :: Michelson.Abs.Data -> Result
transData x = case x of
  Michelson.Abs.DInt int -> failure x
  Michelson.Abs.DStr str -> failure x
  Michelson.Abs.DByte hex -> failure x
  Michelson.Abs.DUnit -> failure x
  Michelson.Abs.DTrue -> failure x
  Michelson.Abs.DFalse -> failure x
  Michelson.Abs.DPair2 pairseq -> failure x
  Michelson.Abs.DLeft data_ -> failure x
  Michelson.Abs.DRight data_ -> failure x
  Michelson.Abs.DSome data_ -> failure x
  Michelson.Abs.DNone -> failure x
  Michelson.Abs.DBlock datas -> failure x
  Michelson.Abs.DMap mapseq -> failure x
  Michelson.Abs.DInstr instr -> failure x

transInstr :: Michelson.Abs.Instr -> Result
transInstr x = case x of
  Michelson.Abs.IBLOCK instrs -> failure x
  Michelson.Abs.IDROP -> failure x
  Michelson.Abs.IDROP_N nat -> failure x
  Michelson.Abs.IDUP -> failure x
  Michelson.Abs.IDUP_N nat -> failure x
  Michelson.Abs.ISWAP -> failure x
  Michelson.Abs.IDIG_N nat -> failure x
  Michelson.Abs.IDUG_N nat -> failure x
  Michelson.Abs.IPUSH typ data_ -> failure x
  Michelson.Abs.ISOME -> failure x
  Michelson.Abs.INONE typ -> failure x
  Michelson.Abs.IUNIT -> failure x
  Michelson.Abs.INEVER -> failure x
  Michelson.Abs.IIF_NONE instrs1 instrs2 -> failure x
  Michelson.Abs.IPAIR -> failure x
  Michelson.Abs.IPAIR_N nat -> failure x
  Michelson.Abs.ICAR -> failure x
  Michelson.Abs.ICDR -> failure x
  Michelson.Abs.IUNPAIR -> failure x
  Michelson.Abs.IUNPAIR_N nat -> failure x
  Michelson.Abs.ILEFT typ -> failure x
  Michelson.Abs.IRIGHT typ -> failure x
  Michelson.Abs.IIF_LEFT instrs1 instrs2 -> failure x
  Michelson.Abs.INIL typ -> failure x
  Michelson.Abs.ICONS -> failure x
  Michelson.Abs.IIF_CONS instrs1 instrs2 -> failure x
  Michelson.Abs.ISIZE -> failure x
  Michelson.Abs.IEMPTY_SET ctyp -> failure x
  Michelson.Abs.IEMPTY_MAP ctyp typ -> failure x
  Michelson.Abs.IEMPTY_BIG_MAP ctyp typ -> failure x
  Michelson.Abs.IMAP instrs -> failure x
  Michelson.Abs.IITER instrs -> failure x
  Michelson.Abs.IMEM -> failure x
  Michelson.Abs.IGET -> failure x
  Michelson.Abs.IGET_N nat -> failure x
  Michelson.Abs.IUPDATE -> failure x
  Michelson.Abs.IUPDATE_N nat -> failure x
  Michelson.Abs.IIF instrs1 instrs2 -> failure x
  Michelson.Abs.ILOOP instrs -> failure x
  Michelson.Abs.ILOOP_LEFT instrs -> failure x
  Michelson.Abs.ILAMBDA typ1 typ2 instrs -> failure x
  Michelson.Abs.IEXEC -> failure x
  Michelson.Abs.IAPPLY -> failure x
  Michelson.Abs.IDIP instrs -> failure x
  Michelson.Abs.IDIP_N nat instrs -> failure x
  Michelson.Abs.IFAILWITH -> failure x
  Michelson.Abs.ICAST -> failure x
  Michelson.Abs.IRENAME -> failure x
  Michelson.Abs.ICONCAT -> failure x
  Michelson.Abs.ISLICE -> failure x
  Michelson.Abs.IPACK -> failure x
  Michelson.Abs.IUNPACK typ -> failure x
  Michelson.Abs.IADD -> failure x
  Michelson.Abs.ISUB -> failure x
  Michelson.Abs.IMUL -> failure x
  Michelson.Abs.IEDIC -> failure x
  Michelson.Abs.IABS -> failure x
  Michelson.Abs.ISNAT -> failure x
  Michelson.Abs.IINT -> failure x
  Michelson.Abs.INEG -> failure x
  Michelson.Abs.ILSL -> failure x
  Michelson.Abs.ILSR -> failure x
  Michelson.Abs.IOR -> failure x
  Michelson.Abs.IAND -> failure x
  Michelson.Abs.IXOR -> failure x
  Michelson.Abs.INOT -> failure x
  Michelson.Abs.ICOMPARE -> failure x
  Michelson.Abs.IEQ -> failure x
  Michelson.Abs.INEQ -> failure x
  Michelson.Abs.ILT -> failure x
  Michelson.Abs.IGT -> failure x
  Michelson.Abs.ILE -> failure x
  Michelson.Abs.IGE -> failure x
  Michelson.Abs.ISELF -> failure x
  Michelson.Abs.ISELF_ADDRESS -> failure x
  Michelson.Abs.ICONTRACT typ -> failure x
  Michelson.Abs.ITRANSFER_TOKENS -> failure x
  Michelson.Abs.ISET_DELEGATE -> failure x
  Michelson.Abs.ICREATE_CONTRACT instrs -> failure x
  Michelson.Abs.IIMPLICIT_ACCOUNT -> failure x
  Michelson.Abs.IVOTING_POWER -> failure x
  Michelson.Abs.INOW -> failure x
  Michelson.Abs.ILEVEL -> failure x
  Michelson.Abs.IAMOUNT -> failure x
  Michelson.Abs.IBALANCE -> failure x
  Michelson.Abs.ICHECK_SIGNATURE -> failure x
  Michelson.Abs.IBLAKE2B -> failure x
  Michelson.Abs.IKECCAK -> failure x
  Michelson.Abs.ISHA3 -> failure x
  Michelson.Abs.ISHA256 -> failure x
  Michelson.Abs.ISHA512 -> failure x
  Michelson.Abs.IHASH_KEY -> failure x
  Michelson.Abs.ISOURCE -> failure x
  Michelson.Abs.ISENDER -> failure x
  Michelson.Abs.IADDRESS -> failure x
  Michelson.Abs.ICHAIN_ID -> failure x
  Michelson.Abs.ITOTAL_VOTING_POWER -> failure x
  Michelson.Abs.IPAIRING_CHECK -> failure x
  Michelson.Abs.ISAPLING_EMPTY_STATE nat -> failure x
  Michelson.Abs.ISAPLING_VERIFY_UPDATE -> failure x
  Michelson.Abs.ITICKET -> failure x
  Michelson.Abs.IREAD_TICKET -> failure x
  Michelson.Abs.ISPLIT_TICKET -> failure x
  Michelson.Abs.IJOIN_TICKETS -> failure x
  Michelson.Abs.IOPEN_CHEST -> failure x

transTypeSeq :: Michelson.Abs.TypeSeq -> Result
transTypeSeq x = case x of
  Michelson.Abs.TTypSeq1 typ1 typ2 -> failure x
  Michelson.Abs.TTypSeq2 typ typeseq -> failure x

transTyp :: Michelson.Abs.Typ -> Result
transTyp x = case x of
  Michelson.Abs.TCtype ctyp -> failure x
  Michelson.Abs.TOption typ -> failure x
  Michelson.Abs.TList typ -> failure x
  Michelson.Abs.TSet ctyp -> failure x
  Michelson.Abs.TOperation -> failure x
  Michelson.Abs.TContract typ -> failure x
  Michelson.Abs.TTicket ctyp -> failure x
  Michelson.Abs.TPair typeseq -> failure x
  Michelson.Abs.TOr typ1 typ2 -> failure x
  Michelson.Abs.TLambda typ1 typ2 -> failure x
  Michelson.Abs.TMap ctyp typ -> failure x
  Michelson.Abs.TBig_map ctyp typ -> failure x
  Michelson.Abs.TBls_g1 -> failure x
  Michelson.Abs.TBls_g2 -> failure x
  Michelson.Abs.TBls_fr -> failure x
  Michelson.Abs.TSapling_transaction nat -> failure x
  Michelson.Abs.TSapling_state nat -> failure x
  Michelson.Abs.TChest -> failure x
  Michelson.Abs.TChest_key -> failure x

transCTypeSeq :: Michelson.Abs.CTypeSeq -> Result
transCTypeSeq x = case x of
  Michelson.Abs.CTypSeq1 ctyp1 ctyp2 -> failure x
  Michelson.Abs.CTypSeq2 ctyp ctypeseq -> failure x

transCTyp :: Michelson.Abs.CTyp -> Result
transCTyp x = case x of
  Michelson.Abs.CUnit -> failure x
  Michelson.Abs.CNever -> failure x
  Michelson.Abs.CBool -> failure x
  Michelson.Abs.CInt -> failure x
  Michelson.Abs.CNat -> failure x
  Michelson.Abs.CString -> failure x
  Michelson.Abs.CChain_id -> failure x
  Michelson.Abs.CBytes -> failure x
  Michelson.Abs.CMutez -> failure x
  Michelson.Abs.CKey_hash -> failure x
  Michelson.Abs.CKey -> failure x
  Michelson.Abs.CSignature -> failure x
  Michelson.Abs.CTimestamp -> failure x
  Michelson.Abs.CAddress -> failure x
  Michelson.Abs.COption ctyp -> failure x
  Michelson.Abs.COr ctyp1 ctyp2 -> failure x
  Michelson.Abs.CPair ctypeseq -> failure x
